SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (1, N'Algorithms and Data Structures', N'Through investigating the everyday life of the algorithm, the book opens a conversation with existing social science research that tends to focus on the power and opacity of algorithms.', N'The Everyday Life of an Algorithm', CAST(275.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (2, N'Algorithms and Data Structures', N'Description This book covers most of commonly used data structures in computer science: abstract data types; Sequences; Dictionaries; Sets; Priority queues; Successors and neighbors; Integer and string searching, etc.', N'Fundamental Data Structures', CAST(48.95 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (3, N'Algorithms and Data Structures', N'An accessible introduction to algorithms, explaining not just what they are but how they work, with examples from a wide range of application areas.', N'Algorithms', CAST(19.50 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (4, N'Algorithms and Data Structures', N'This book written to provide clear and concise explanation of topics for programmers both starting to learn the Algorithms as well as those diving in more complex topics.', N'Essential Algorithms', CAST(34.95 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (5, N'Database Theory and Systems', N'This book is a practical guide for serious game developers', N'Data-Oriented Design:', CAST(79.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (6, N'Database Theory and Systems', N'his book discusses database logical and physical design, and introduces you to the SQL language.', N'Database Fundamentals', CAST(16.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (7, N'Database Theory and Systems', N'This book covers database systems and database design concepts.', N' Database Design, 2nd Edition', CAST(29.95 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (8, N'Computer Programming', N'Unlike other introductory books, it focuses on the program design process, presenting program design guidelines', N'How to Design Programs', CAST(75.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (9, N'Computer Programming', N'The book shows that algorithms implemented in a real programming language, such as C++', N'Elements of Programming', CAST(120.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (10, N'Computer Programming', N'This book provides a quick introduction to the PureBasic programming language.', N'PureBasic - A Beginner''s Guide To Computer Programming', CAST(120.00 AS Decimal(18, 2)))
INSERT INTO [dbo].[Products] ([ProductID], [Category], [Description], [Name], [Price]) VALUES (11, N'Computer Programming', N'The authors put classes and the design of classes into the center of their approach. ', N'How to Design Classes', CAST(120.00 AS Decimal(18, 2)))
SET IDENTITY_INSERT [dbo].[Products] OFF

Delete Products
